### ISSUE TITLE
Loosen cython reqs

### ISSUE THREAD

**Issue by brisvag** [pyapp-kit/in-n-out#65]
When trying to update napari's packages for archlinux, I got stuck at in-n-out requiring a specific (non-latest) version of cython. As far as I can tell, everything builds fine with a later version (currently testes `3.0.0b3` instead of `3.0.0a11`. Can we loosed these requirements here, or should I work around it downstream?

**Comment by tlambert03** [comment]
Yeah, it's actually not even using cython (it was experimental).. Will do

**Comment by tlambert03** [comment]
have another try with 0.1.8

**Comment by brisvag** [comment]
All good! There's some interesting changes with the name of the package in a few places (pypi download link and tarball mainly), where it was slugified. Maybe a change in `pypi`?

**Comment by tlambert03** [comment]
I switched to hatchling... probably that
