### ISSUE TITLE
Mock obj `resolve_single_type_hints` results in empty `globalns`, preventing resolve

### ISSUE THREAD

**Issue by lucyleeow** [pyapp-kit/in-n-out#74]
### Description

In `type_resolved_signature` if `hints.update(resolve_type_hints(func, localns=localns))` errors, all parameters in `sig` are resolved using `_resolve_params_one_by_one`:

https://github.com/pyapp-kit/in-n-out/blob/83ecfcb9f700350d72eb7cd453f5f86e0630d5a4/src/in_n_out/_type_resolution.py#L176-L189

This calls `resolve_single_type_hints` which creates a mock object. When we later use `typing.get_type_hints` we [get the global namespace](https://github.com/python/cpython/blob/67e8d416cc5e14c181e4f883ffb4d87f2a647ae1/Lib/typing.py#L2184), which for this mock object is empty. This means that if one parameter has an unresolvable type annotation, other parameters may be not resolved. (The `globalns` of the original object would have the required objects)

Note that this is for cases where `from __future__ import annotations` is used.

### What I Did

Results in using `_resolve_params_one_by_one`:
```python
from __future__ import annotations

from in_n_out import type_resolved_signature
from app_model import Action
from magicgui.widgets import FunctionGui

def outer():

    def myfun(a: 'unknown', b: FunctionGui):
        if isinstance(a, FunctionGui):
            return a

    return Action(id='test', title='title', callback=myfun)

act = outer()
a = type_resolved_signature(act.callback, raise_unresolved_optional_args=False, raise_unresolved_required_args=False)
print(a)
```

Gives:

```
(a: "'unknown'", b: 'FunctionGui')
```

Whereas if I used instead `def myfun(a: str, b: FunctionGui):`, `b` does resolve properly:

```
(a: str, b: magicgui.widgets._function_gui.FunctionGui)
```

I would always expect `b` to resolve properly regardless of what the other parameter annotations are.

**Comment by lucyleeow** [comment]
@tlambert03 this is not causing any problems atm (changed the way I implemented things) but for future it would be good if the resolving was more consistent. Thank you.

**Comment by tlambert03** [comment]
having a look now, thanks!

**Comment by lucyleeow** [comment]
I just realised the example is probably more complicated than it needs to be, a simple function definition would probably work, the example was from when I was yet to figure out the `from __future__ import annotations` part.
